apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config

data:
  PORT: "4000"
  NODE_ENV: "production"
  AWS_REGION: "ap-south-1"
  DYNAMO_MENU_TABLE: "CafeMenuItems"
  DYNAMO_ORDERS_TABLE: "CafeOrders"
  CLIENT_ORIGIN: "YOUR_FRONTEND_URL"